### ISSUE TITLE
Техническое задание

### ISSUE THREAD

**Issue by Sammers21** [PAIS-Lab-Public-Projects/Gena-CommFSM#1]
ГОСТ 19.201-78

http://www.rugost.com/index.php?option=com_content&view=article&id=105:19-1-3&catid=25&Itemid=62

http://www.rugost.com/index.php?option=com_content&view=article&id=106:19-4-8&catid=25&Itemid=62

**Comment by Sammers21** [comment]
Пункты 1-3 готовы

**Comment by Sammers21** [comment]
@mitsyuk , как называется язык, на котором будет описана система конечных автоматов?

**Comment by Sammers21** [comment]
@mitsyuk предварительная версия тз готова. Её можно найти в гугл-диске в папке документация. Жду ваших замечаний и предложений.

**Comment by mitsyuk** [comment]
Комментарии в документе.

**Comment by Sammers21** [comment]
@mitsyuk , вроде ответил на все ваши комментарии. Можете взглянуть на них еще раз?

**Comment by Sammers21** [comment]
@mitsyuk, могу загружать документ в LMS?

**Comment by mitsyuk** [comment]
@Sammers21 Загружайте. Считаем, что первая версия готова.

**Comment by Sammers21** [comment]
Загрузил
