### ISSUE TITLE
CSV logger

### ISSUE THREAD

**Issue by Sammers21** [PAIS-Lab-Public-Projects/Gena-CommFSM#12]

**Comment by Sammers21** [comment]
![image](https://user-images.githubusercontent.com/16746106/34468282-da327cdc-ef16-11e7-81b3-25c57b42918d.png)
работает

**Comment by Sammers21** [comment]
@mitsyuk, по поводу event-type поля. В данном случае я вывожу. _$автомат-$откуда-$куда-$codition_. Это корректно?

**Comment by mitsyuk** [comment]
@Sammers21 Часть "$откуда-$куда" должна отключаться.
"$codition" - видимо, condition? Состояние канала сообщений?

**Comment by Sammers21** [comment]
Сделать опция, _-show-states_, '-show-conditions', а писать в лог _$автомат-$имя_перехода_ по умолчанию

**Comment by Sammers21** [comment]
Сделано
