### ISSUE TITLE
Условия остановки minig'a 

### ISSUE THREAD

**Issue by Sammers21** [PAIS-Lab-Public-Projects/Gena-CommFSM#15]
А какие у нас будут вообще условия остановки майнинга? 
На данный случай я так понимаю единственный правилом остановки является переход автомата в FINAL состояние?

**Comment by Sammers21** [comment]
Или может имеет смысл сделать опцию, которая будет задавать максимальное количество переходов в рамках одной штрассы?

**Comment by mitsyuk** [comment]
@Sammers21 
Возможны следующие ситуации:
1 циклов нет. Тогда автоматы должны все быть в FINAL состоянии (успешный останов), либо какой-то не в FINAL, но сработать не может ни один переход (попали в тупик).
2 циклы есть (потенциально бесконечное исполнение). Тогда должна быть опция максимального количества трасс. Начало трассы - все автоматы в начальном состоянии. Конец трассы - все автоматы в финальном состоянии, следующее состояние после этого должно быть началом новой трассы. Т.е., когда все автоматы оказались в финальном состоянии, после чего один из всех перешёл в своё начальное состояние (цикл), надо последующим событиям, связанным с этим автоматом, присваивать новый идентификатор трассы. А другие автоматы получат этот же идентификатор, когда также перейдут в начальное состояние. Пока не побывали в начальном состоянии, считаем, что идёт старая трасса. Когда нагенерили N трасс с успешным завершением, останавливаем генерацию. В случае потоковой генерации, надо прекращать "по кнопке".
Для случая попадания в бесконечный цикл где-то по ходу исполнения надо предусмотреть также максимальное количество переходов в одной трассе, задаваемое пользователем. Пусть, например, по умолчанию будет 10000, но пользователь должен иметь возможность изменять это количество.
