### ISSUE TITLE
Конфигурация приоритета перехода

### ISSUE THREAD

**Issue by Sammers21** [PAIS-Lab-Public-Projects/Gena-CommFSM#18]
Я так понимаю, что были какие-то идеи по поводу задания приоритета переходу. В данный момент у нас случайная генерация. 

Какие могут быть варианты? У нас скажем есть 10 переходов доступных(из разных автоматов), какие могут быть стратегии выбора помимо случайной? Напрашиваются варианты с системой весов....

**Comment by mitsyuk** [comment]
@Sammers21  предлагаю обсудить на ближайшей встрече, долго писать и требуется обсуждение.
