### ISSUE TITLE
Написание спецификации формата описания системы конечных автоматов

### ISSUE THREAD

**Issue by Sammers21** [PAIS-Lab-Public-Projects/Gena-CommFSM#2]

**Comment by Sammers21** [comment]
@mitsyuk , Первоначальная версия спецификации готова. Предлагаю вам взглянуть на нее. Если есть какие-либо замечания, то неприменно высказать их.

**Comment by mitsyuk** [comment]
@Sammers21 Посмотрел на первоначальную версию, внёс кое-какие правки. Задал один важный вопрос (и несколько несущественных).

**Comment by Sammers21** [comment]
@mitsyuk , вроде поправил. Взгляните пожалуйста еще раз

**Comment by mitsyuk** [comment]
@Sammers21 Всё ок, мне кажется. Можно двигаться дальше. Новые изменения, если потребуются, будем вносить по ходу дела.
