### ISSUE TITLE
Спецификация алгоритма генерации

### ISSUE THREAD

**Issue by Sammers21** [PAIS-Lab-Public-Projects/Gena-CommFSM#7]
Начал работать

**Comment by Sammers21** [comment]
@mitsyuk , алгоритм можно смотреть

**Comment by mitsyuk** [comment]
Кое-что изменил. 
Лучше писать на англ., будет проще.
Посмотрите на замечания. 

Стоит сразу собирать список возможных настроек (они могут влиять на устройство алгоритма).

**Comment by mitsyuk** [comment]
@Sammers21
